version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "stop-words"
    groups:
      minor-and-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "https://github.com/astral-sh/ruff-pre-commit"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
