# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  # Following <https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry>
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --directory=python --with dev

# Build documentation with MkDocs
mkdocs:
  configuration: python/mkdocs.yml
