"""Tests for bin/build_redirects.py."""

import re
import sys
import textwrap
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from bin.build_redirects import RedirectConfigError, build_redirects, load_redirects


HTACCESS_TEMPLATE = """RewriteEngine On
# BEGIN GENERATED REDIRECTS
# END GENERATED REDIRECTS
RewriteRule ^other$ somewhere [L]
"""


def write_config(tmp_path: Path, redirects: str) -> Path:
    config_path = tmp_path / "redirects.yaml"
    config_path.write_text(
        "version: 1\n"
        "batches:\n"
        "  - added: 2026-09-09\n"
        "    issues: [123, 456]\n"
        "    redirects:\n"
        f"{textwrap.indent(redirects, '    ')}",
        encoding="utf-8",
    )
    return config_path


def build(tmp_path: Path, redirects: str, *, use_rewrite_map: bool = False):
    config_path = write_config(tmp_path, redirects)
    template_path = tmp_path / ".htaccess.in"
    output_path = tmp_path / ".htaccess"
    map_path = tmp_path / ".acl-redirects.map"
    template_path.write_text(HTACCESS_TEMPLATE, encoding="utf-8")
    build_redirects(
        config_path=config_path,
        htaccess_template_path=template_path,
        htaccess_output_path=output_path,
        map_output_path=map_path,
        base_url="https://preview.example.test/branch",
        use_rewrite_map=use_rewrite_map,
    )
    return output_path.read_text(), map_path.read_text()


def test_exact_permanent_redirect_uses_map(tmp_path):
    htaccess, redirect_map = build(
        tmp_path,
        """  - from: /old/
    to: /new/
""",
        use_rewrite_map=True,
    )

    assert "${acl_redirects:%{REQUEST_URI}|NOT_FOUND}" in htaccess
    assert "RewriteRule ^old/" not in htaccess
    assert "/old/ https://preview.example.test/branch/new/" in redirect_map


def test_non_map_redirects_generate_ordered_rules(tmp_path):
    htaccess, redirect_map = build(
        tmp_path,
        """  - from: /old/
    to: /new/
  - match: prefix
    from: /legacy/
    to: /current/
    status: 302
    query: discard
    note: Temporary migration
    tests:
      - from: /legacy/document
        to: /current/document
  - match: regex
    from: '^/docs/([0-9]+)/?$'
    to: '/papers/$1/'
    query: preserve
    tests:
      - from: /docs/17/
        to: /papers/17/
  - from: /removed
    status: 410
""",
    )

    expected_lines = [
        "RewriteRule ^old/$ https://preview.example.test/branch/new/ [R=301,END]",
        "RewriteRule ^removed$ - [G]",
        "RewriteRule ^legacy/(.*)$ https://preview.example.test/branch/current/$1 [R=302,END,QSD]",
        "RewriteRule ^docs/([0-9]+)/?$ https://preview.example.test/branch/papers/$1/ [R=301,END]",
    ]
    positions = [htaccess.index(line) for line in expected_lines]
    assert positions == sorted(positions)
    assert (
        redirect_map
        == "# Generated by bin/build_redirects.py; do not edit.\n# added 2026-09-09; issues 123, 456\n/old/ https://preview.example.test/branch/new/\n"
    )


def test_prefix_suffix_is_inserted_before_target_query(tmp_path):
    htaccess, _ = build(
        tmp_path,
        """  - match: prefix
    from: /legacy/
    to: /current/?source=legacy
    query: append
    tests:
      - from: /legacy/document
        to: /current/document?source=legacy
""",
    )

    assert (
        "RewriteRule ^legacy/(.*)$ "
        "https://preview.example.test/branch/current/$1?source=legacy "
        "[R=301,END,QSA]"
    ) in htaccess


def test_prefix_gone_redirect_matches_without_target(tmp_path):
    htaccess, _ = build(
        tmp_path,
        """  - match: prefix
    from: /withdrawn/
    status: 410
    tests:
      - from: /withdrawn/document
""",
    )

    assert "RewriteRule ^withdrawn/(.*)$ - [G]" in htaccess


@pytest.mark.parametrize(
    ("redirects", "message"),
    [
        (
            """  - match: regex
    from: '/old/(.*)'
    to: '/new/$1'
    tests:
      - from: /old/value
        to: /new/value
""",
            "must start with '^/' and end with '$'",
        ),
        (
            """  - from: /one
    to: /two
  - from: /two
    to: /three
""",
            "redirect chain",
        ),
        (
            """  - match: regex
    from: '^/old/([0-9]+)$'
    to: '/new/$2'
    tests:
      - from: /old/7
        to: /new/7
""",
            "missing capture group",
        ),
        (
            """  - match: prefix
    from: /old/
    to: /new/
""",
            "prefix redirects require at least one test",
        ),
        (
            """  - from: /one
    to: /legacy/document
  - match: prefix
    from: /legacy/
    to: /current/
    tests:
      - from: /legacy/document
        to: /current/document
""",
            "redirect chain",
        ),
        (
            """  - from: /old
    to: /new%20name
""",
            "unsafe Apache expansion syntax",
        ),
        (
            """  - match: regex
    from: '^/old/(.*)$'
    to: '/new/$0'
    tests:
      - from: /old/value
        to: /new/value
""",
            "unsafe Apache expansion syntax",
        ),
        (
            """  - from: /old
    to: 'https://['
""",
            "target is not a valid URL",
        ),
        (
            """  - from: /old
    to: /new
    match: []
""",
            "match must be one of",
        ),
        (
            """  - from: /old
    to: /new
    status: []
""",
            "status must be one of",
        ),
        (
            """  - from: /old
    to: /new
    query: []
""",
            "query must be one of",
        ),
    ],
)
def test_invalid_configuration_is_rejected(tmp_path, redirects, message):
    config_path = write_config(tmp_path, redirects)

    with pytest.raises(RedirectConfigError, match=re.escape(message)):
        load_redirects(config_path)


@pytest.mark.parametrize(
    ("batch", "message"),
    [
        (
            """  - added: not-a-date
    issues: [123]
    redirects:
      - from: /old
        to: /new
""",
            "added must be an ISO date",
        ),
        (
            """  - added: 2026-09-09
    issues: []
    redirects:
      - from: /old
        to: /new
""",
            "issues must be a non-empty list",
        ),
        (
            """  - added: 2026-09-09
    issues: [123, 123]
    redirects:
      - from: /old
        to: /new
""",
            "issue numbers must not be repeated",
        ),
        (
            """  - added: 2026-09-09
    issues: [123]
    redirects:
      - from: /old
        to: /new
  - added: 2026-09-09
    issues: [456]
    redirects:
      - from: /other
        to: /elsewhere
""",
            "duplicate added date",
        ),
    ],
)
def test_invalid_batch_metadata_is_rejected(tmp_path, batch, message):
    config_path = tmp_path / "redirects.yaml"
    config_path.write_text(f"version: 1\nbatches:\n{batch}", encoding="utf-8")

    with pytest.raises(RedirectConfigError, match=re.escape(message)):
        load_redirects(config_path)


def test_boolean_version_is_rejected(tmp_path):
    config_path = tmp_path / "redirects.yaml"
    config_path.write_text("version: true\nbatches: []\n", encoding="utf-8")

    with pytest.raises(RedirectConfigError, match="unsupported redirect.*version"):
        load_redirects(config_path)


def test_checked_in_registry_compiles(tmp_path):
    repository_root = Path(__file__).resolve().parent.parent
    output_path = tmp_path / ".htaccess"
    map_path = tmp_path / ".acl-redirects.map"

    build_redirects(
        config_path=repository_root / "hugo" / "redirects.yaml",
        htaccess_template_path=repository_root / "hugo" / "static" / ".htaccess",
        htaccess_output_path=output_path,
        map_output_path=map_path,
        base_url="https://aclanthology.org",
        use_rewrite_map=True,
    )

    htaccess = output_path.read_text()
    assert "# added 2026-09-09; issues 9364, 9908" in htaccess
    assert "https://aclanthology.org/2026.lrec-1$1" in htaccess
    assert "2026.lrec-main.104" not in htaccess
    assert "Options -Indexes" in htaccess
