name: Correction to Author Page
description: Fix issues with author pages.
title: "Author Page: {replace with author name}"
labels: ["correction", "author-page"]
assignees:
  - anthology-assist
body:
  - type: markdown
    attributes:
      value: >
        This form will report issues with author pages. There are two situations: (1) merging and (2) splitting.
        Merging gathers all of an author's papers under a single name, even if they were published under variants
        of the author's name, while splitting allows the separation of papers published under the same
        name but belonging to different people.
  - type: checkboxes
    id: in_anth_check
    attributes:
      label: Confirming that Author is Published in the Anthology
      description: |
        The Anthology only hosts publications submitted by certain venues (conferences/journals), and only has pages
        for authors of these publications (not individually created user profiles).
      options:
        - label: I confirm that this concerns an author who already has at least one publication in the Anthology.
          required: True
  - type: checkboxes
    id: name_correction_check
    attributes:
      label: Confirming that Paper Metadata is Correct
      description: |
        Anthology policy is that the metadata (i.e., what appears on the web pages) should match what is displayed on the PDF exactly, including any middle names and/or initials of authors.
        If this is not the case, **you must first use the "Fix data" button on each affected paper's page to correct this** (e.g., https://aclanthology.org/1962.earlymt-1.6/) before submitting an author correction.  This form should _only_ be used if there are issues that remain after fixing all the author metadata.
      options:
        - label: I confirm that all affected papers show the exact same names on the website as on the PDF.
          required: True
  - type: textarea
    id: name_pages_affected
    attributes:
      label: Author Pages
      description: |
        Which author page(s) are affected by this correction? Please list the URL of every affected author page here.
      placeholder: ex. https://aclanthology.org/people/matt-post
    validations:
      required: true

  - type: textarea
    id: author_orcid
    attributes:
      label: Author ORCID
      description: |
        Provide a valid [ORCID](https://orcid.org) link here, and [add your name variants to your ORCID profile](https://aclanthology.org/info/orcid_id). This will be used to match papers to your Anthology ID.
      placeholder: ex. https://orcid.org/0009-0003-8868-7504
    validations:
      required: true
  - type: textarea
    id: author_highest_degree_institution
    attributes:
      label: Institution of highest (anticipated) degree
      description: |
        Provide the name of the school or university where you have or will receive your highest degree (e.g.,
        current affiliation for students, Ph.D. institution for faculty and industry researchers). This will be used
        to form your author page ID, if needed.
      placeholder: ex. Johns Hopkins University (https://www.jhu.edu/)
    validations:
      required: true
  - type: textarea
    id: author_name_script_variant
    attributes:
      label: Author Name (only if published in another script)
      description: |
        If you publish using your name written in a non-Latin script, please provide it here with a UTF-8 encoding.
      placeholder: ex. अंकुर
    validations:
      required: false
  - type: checkboxes
    id: author_name_script_variant_direction
    attributes:
      label: Is the authors name read right to left? (only if published in another script)
      options:
        - label: Script is read right-to-left.
          required: false
  - type: checkboxes
    id: name_correction_type
    attributes:
      label: Type of Author Metadata Correction
      description: What kind of request is this?
      options:
        - label: "Split/disambiguate: The author page includes papers from two or more different people."
        - label: "Merge profiles: A single author has multiple profiles with different spellings or variants of their name."
        - label: "Name change: This author has permanently changed their name."
    validations:
      required: true
  - type: textarea
    id: name_change_description
    attributes:
      label: Supporting Information
      description: |
        We may need further information to address your problem.
          - If you want to split author pages, **please provide a link to every paper of yours** in the Anthology (third party sites such as Google Scholar are not useful).
          - If you are asking to merge author pages, after ensuring every name matches the PDF, make sure to list which name is the preferred / canonical one.
    validations:
      required: true
