name: Correction to Author Page
description: Fix issues with author pages.
title: "Author Page: {replace with author name}"
labels: ["correction", "metadata"]
assignees:
  - anthology-assist
body:
  - type: markdown
    attributes:
      value: >
        This form will report issues with author pages—for example, if a name needs to be disambiguated,
        or if two versions of a name should be mapped to the same individual.
        For cases where an individual has published under multiple name variants, submitting a pull request
        that modifies [`name_variants.yaml`](https://github.com/acl-org/acl-anthology/blob/master/data/yaml/name_variants.yaml)
        directly will expedite the process. If an author name listed for a paper does not match
        what is in the PDF, instead use the "Fix data" button on the paper page,
        which will help automate the correction. Thanks!
  - type: textarea
    id: name_pages_affected
    attributes:
      label: Author Pages
      description: |
        Which author page(s) are affected by this correction? Please only give one or more URLs of author pages here.
      placeholder: ex. https://aclanthology.org/people/m/matt-post/
    validations:
      required: true
  - type: checkboxes
    id: name_correction_type
    attributes:
      label: Type of Author Metadata Correction
      description: "Please indicate which issue(s) should be corrected regarding the author page(s)."
      options:
        - label: The author page wrongly conflates different people with the same name.
        - label: This author has multiple pages with different spellings of their name.
        - label: This author has permanently changed their name.
    validations:
      required: true
  - type: textarea
    id: name_change_description
    attributes:
      label: Supporting Information
      description: |
        Please provide as much information as possible to help us fix the issue.  For example:
          - Describe what the correct author page(s) should look like.
          - Provide a link to the academic website of the author(s) that helps us verify their current name or publication list.
          - If there are multiple spellings of the name, indicate which spelling of the name is the preferred/canonical one. _(e.g. if you are submitting a correction for yourself)_
    validations:
      required: true
