name: Correction to Author Page
description: Fix issues with author pages.
title: "Author Page: {replace with author name}"
labels: ["correction", "metadata"]
assignees:
  - anthology-assist
body:
  - type: markdown
    attributes:
      value: >
        This form will report issues with author pages—for example, if a name needs to be disambiguated,
        or if two versions of a name should be mapped to the same individual.
        For cases where an individual has published under multiple name variants, submitting a pull request
        that modifies [`name_variants.yaml`](https://github.com/acl-org/acl-anthology/blob/master/data/yaml/name_variants.yaml)
        directly will expedite the process. If an author name listed for a paper does not match
        what is in the PDF, instead use the "Fix data" button on the paper page,
        which will help automate the correction. Thanks!
  - type: textarea
    id: name_pages_affected
    attributes:
      label: Author Pages
      description: |
        Which author page(s) are affected by this correction? Please list the URL of every affected author page here.
      placeholder: ex. https://aclanthology.org/people/m/matt-post/
    validations:
      required: true
  - type: textarea
    id: author_orcid
    attributes:
      label: Author ORCID
      description: |
        Please provide a valid ORCID link here. This will be used to help match future papers to your Anthology ID.
      placeholder: ex. https://orcid.org/my-orcid?orcid=0009-0003-8868-7504
    validations:
      required: true
  - type: textarea
    id: author_highest_degree_institution
    attributes:
      label: Institution of highest (anticipated) degree
      description: |
        Please provide the name of the school or university where you have or will receive your highest degree (e.g.,
        current affiliation for students, Ph.D. institution for faculty and industry researchers). This will be used
        to form your author page ID, if needed.
      placeholder: ex. Johns Hopkins University (https://www.jhu.edu/)
    validations:
      required: true
  - type: checkboxes
    id: name_correction_type
    attributes:
      label: Type of Author Metadata Correction
      description: "Please indicate which issue(s) should be corrected regarding the author page(s)."
      options:
        - label: The author page includes papers from two or more different people.
        - label: A single author has multiple pages with different spellings or variants of their name.
        - label: This author has permanently changed their name.
    validations:
      required: true
  - type: checkboxes
    id: name_correction_check
    attributes:
      label: Confirming that Paper Metadata is Correct
      description: |
        Anthology policy is that author metadata should match what is displayed
        on the PDF. To fix discrepancies, **this is not the correct issue template to use.** 
        Instead, please use the "Fix data" button on the affected paper page(s) to
        correct the name displayed on the ACL Anthology.
      options:
        - label: I have made sure that the names given for each of the author's papers match the name shown on the PDF.
          required: True
  - type: textarea
    id: name_change_description
    attributes:
      label: Supporting Information
      description: |
        Please provide as much information as possible to help us fix the issue.  For example:
          - Describe what the correct author page(s) should look like.
          - Provide a link to the academic website of the author(s) that helps us verify their current name or publication list.
          - If there are multiple spellings of the name, indicate which spelling of the name is the preferred/canonical one. _(e.g. if you are submitting a correction for yourself)_
    validations:
      required: true
