name: Bulk Correction to Paper Metadata
description: Fix typos or errors in a paper's title, abstract, or author names.
labels: ["correction", "metadata"]
assignees:
  - anthology-assist
body:
  - type: markdown
    attributes:
      value: >
        This form is activated by following a link from each paper page in the Anthology (e.g., https://preview.aclanthology.org/autopr/K17-1003/). The form will list the title, abstract, and authors in JSON format, which you can manipulate to make corrections, such as adjusting a title, correcting an author name, adding a missing author, or reordering names.

        Please note to take care to preserve structure such as the `<fixed-case>` tag that is sometimes present in titles.

        Corrections will be processed in bulk on a weekly basis after verification by Anthology staff.
  - type: textarea
    id: data
    attributes:
      label: JSON code block
      description: Please make corrections below, taking care to preserve the JSON structure (e.g., no trailing commas at the end of lists). If you add an author, do not worry about the ID unless you know what it is.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Note:** If you request an author name correction for yourself, please help ensure your name is correct for future publications by setting it correctly in Softconf/OpenReview.
