blank_issues_enabled: true
contact_links:
  - name: Correction to Code or Data Metadata
    url: https://paperswithcode.com/
    about: 'Please edit wrong or missing "Code" and "Data" links directly on Papers With Code.'
