name: Ingestion request
description: Register your conference or workshop
title: "[Ingestion Request]: "
labels: ["ingestion"]
assignees:
  - mjpost
body:
  - type: markdown
    attributes:
      value: |
        Please use this template to [register your intent](https://aclanthology.org/info/contrib/#register-your-meeting) to submit proceedings to the ACL Anthology.
        This form replaces our earlier use of spreadsheets to handle this process.
        **We would be grateful** if you were to carefully read [the instructions](https://aclanthology.org/info/contrib/) which should answer many questions and ease this process.

Please provide the following information.

* Release date: YYYY-MM-DD
* Website: https://example.com
* 

## Release date

Please replace this text with the date you would like your proceedings to be made available on the Anthology.
Please note:
* There are often patent and IP issues with the date, which
* The

## List of volumes

Please list all volumes that will be ingested.

1. (Venue ID, volume name

(venue ID, volume, 


(1) The full title: The Third Workshop on Financial Technology and Natural Language Processing

(2) The publishing date: August 10th, 2021

(3) Event Type: non-ACL event. (In conjunction with IJCAI-2021)

(4) Workshop Site: https://sites.google.com/nlg.csie.ntu.edu.tw/finnlp2021/

(5) Conference Management Tool: EasyChair

(6) Submission Site: https://easychair.org/conferences/?conf=finnlp2021

(7) Contact Email: [redacted]

(8) The proceedings of the prior workshop:
2019: https://www.aclweb.org/anthology/events/ws-2019/#w19-55
2020: https://www.aclweb.org/anthology/events/coling-2020/#2020-finnlp-1
