#!/usr/bin/env python3

import xml.etree.ElementTree as ET
import collections
import sys
from common import *

if __name__ == "__main__":
    c = collections.defaultdict(collections.Counter)
    for xmlfile in sys.argv[1:]:
        tree = ET.parse(xmlfile)
        for paper in tree.getroot().findall('paper'):
            for abstract in paper.findall('abstract'):
                for w in tokenize(get_text(abstract)):
                    c[w.lower()][w] += 1
    truelist = []
    for w_lower in c:
        if w_lower in falselist: continue
        if w_lower != max(c[w_lower], key=c[w_lower].get):
            for w in c[w_lower]:
                if fixedcase_word(w) == None:
                    truelist.append(w)
    truelist.sort()
                    
    with open("truelist", "w") as outfile:
        print("# Automatically generated by train.py", file=outfile)
        for w in truelist:
            print(w, file=outfile)
