name: Check website build

on:
  pull_request:
    branches:
      - master

# only run one at a time per branch
concurrency:
  group: check-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-build:
    runs-on:
      labels: ubuntu-latest-m
    steps:
    - uses: actions/checkout@v7

    - id: prerequisites
      uses: ./.github/actions/install-build-prerequisites

    - name: Run Python library integration tests
      run: uv run --locked pytest -m "integration"
      working-directory: ./python

    - name: Build website
      run: make check site
