name: Add link and image to metadata issue

on:
  issues:
    types: [opened]

jobs:
  process-anthology-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check issue labels
        id: check-labels
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const labels = issue.labels.map(label => label.name);
            const hasRequiredLabels =
              labels.includes('correction') &&
              labels.includes('metadata');

            if (!hasRequiredLabels) {
              core.setFailed('Required labels not present');
              return;
            }

            const body = issue.body;
            if (!body.includes('```json')) {
              core.setFailed('Issue does not start with JSON code block');
              return;
            }

            try {
              const jsonContent = body.split('```json')[1].split('```')[0].trim();
              const data = JSON.parse(jsonContent);

              if (!data.anthology_id) {
                core.setFailed('No anthology_id found in JSON');
                return;
              }

              core.setOutput('anthology_id', data.anthology_id);
            } catch (error) {
              core.setFailed(`Error parsing JSON: ${error.message}`);
            }

      - name: Create comment
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            const anthology_id = steps.check-labels.outputs.anthology_id;
            const comment = `
            Found ACL Anthology entry:

            📄 Paper: https://aclanthology.org/${anthology_id}

            ![Thumbnail](https://aclanthology.org/thumb/${anthology_id}.jpg)
            `;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
