name: Merge PRs from acl-pwc-bot

on:
  # Triggers when the required build check is completed
  workflow_run:
    types:
      - completed
    workflows:
      - 'check-build'

jobs:
  merge-me:
    name: Merge PR if it's by acl-pwc-bot
    runs-on: ubuntu-latest
    steps:
      - # Only attempt merge when the check was a success
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        name: Merge PR
        uses: ridedott/merge-me-action@v2
        with:
          # Merge only PRs by acl-pwc-bot this way
          GITHUB_LOGIN: acl-pwc-bot
          # Merge with acl-pwc-bot credentials, so the merge will trigger our
          # deployment workflow
          GITHUB_TOKEN: ${{ secrets.PWC_BOT_TOKEN }}
          MERGE_METHOD: SQUASH
