name: print-info

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened]

jobs:
  add-review-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Print event details
        run: |
          cat << "END_OF_BLOCK"
          Event Name: ${{ github.event_name }}
          Action: ${{ github.event.action }}
          PR Title: ${{ github.event.pull_request.title }}
          Original PR Body: ${{ github.event.pull_request.body }}
          END_OF_BLOCK
