name: print-info

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened]

jobs:
  add-review-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Print event details
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
